# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/01-aks-demo/'
    backendServiceArm: 'Demo-Sandbox-9'
    backendAzureRmResourceGroupName: 'viresh-tfstate-rg-donotdelete'
    backendAzureRmStorageAccountName: 'vireshtesttfstatesa'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: '01aksdemo'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/01-aks-demo/'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/01-aks-demo/'
    environmentServiceNameAzureRM: 'Demo-Sandbox-9'